const MOVIES = [
    {
        "id": "1",
        "name": "The Dark Knight",
        "genre": "Action, Crime, Drama",
        "premiere": "2008-07-14",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://cdn.vox-cdn.com/thumbor/Kr_zFMNcZmn28_TBF-8YYlhD9gw=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/11694967/0_c9S8ajFBpwX89ZuU.jpeg",
        "projection_type": "2D"
    },
    {
        "id": "2",
        "name": "Inception",
        "genre": "Action, Adventure, Sci-Fi",
        "premiere": "2010-07-08",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://pics.filmaffinity.com/Inception-652954101-large.jpg",
        "projection_type": "3D"
    },
    {
        "id": "3",
        "name": "The Shawshank Redemption",
        "genre": "Drama",
        "premiere": "1994-09-22",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_shawshank_redemption.jpg",
        "projection_type": "2D"
    },
    {
        "id": "4",
        "name": "The Godfather",
        "genre": "Crime, Drama",
        "premiere": "1972-03-15",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_godfather.jpg",
        "projection_type": "2D"
    },
    {
        "id": "5",
        "name": "Pulp Fiction",
        "genre": "Crime, Drama",
        "premiere": "1994-05-21",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/pulp_fiction.jpg",
        "projection_type": "2D"
    },
    {
        "id": "6",
        "name": "The Matrix",
        "genre": "Action, Sci-Fi",
        "premiere": "1999-03-31",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_matrix.jpg",
        "projection_type": "3D"
    },
    {
        "id": "7",
        "name": "Forrest Gump",
        "genre": "Drama, Romance",
        "premiere": "1994-06-23",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/forrest_gump.jpg",
        "projection_type": "2D"
    },
    {
        "id": "8",
        "name": "Star Wars: Episode IV - A New Hope",
        "genre": "Action, Adventure, Fantasy",
        "premiere": "1977-05-25",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/star_wars_episode_iv.jpg",
        "projection_type": "3D"
    },
    {
        "id": "9",
        "name": "The Silence of the Lambs",
        "genre": "Crime, Drama, Thriller",
        "premiere": "1991-02-14",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_silence_of_the_lambs.jpg",
        "projection_type": "2D"
    },
    {
        "id": "10",
        "name": "The Lord of the Rings: The Fellowship of the Ring",
        "genre": "Action, Adventure, Drama",
        "premiere": "2001-12-10",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_lord_of_the_rings_fellowship.jpg",
        "projection_type": "3D"
    },
    {
        "id": "11",
        "name": "The Lion King",
        "genre": "Animation, Adventure, Drama",
        "premiere": "1994-06-15",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_lion_king.jpg",
        "projection_type": "2D"
    },
    {
        "id": "12",
        "name": "Titanic",
        "genre": "Drama, Romance",
        "premiere": "1997-12-19",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/titanic.jpg",
        "projection_type": "2D"
    },
    {
        "id": "13",
        "name": "Jurassic Park",
        "genre": "Action, Adventure, Sci-Fi",
        "premiere": "1993-06-09",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/jurassic_park.jpg",
        "projection_type": "3D"
    },
    {
        "id": "14",
        "name": "Avatar",
        "genre": "Action, Adventure, Fantasy",
        "premiere": "2009-12-16",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/avatar.jpg",
        "projection_type": "3D"
    },
    {
        "id": "15",
        "name": "Interstellar",
        "genre": "Adventure, Drama, Sci-Fi",
        "premiere": "2014-10-26",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/interstellar.jpg",
        "projection_type": "3D"
    },
    {
        "id": "16",
        "name": "E.T. the Extra-Terrestrial",
        "genre": "Family, Sci-Fi",
        "premiere": "1982-06-11",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/et.jpg",
        "projection_type": "2D"
    },
    {
        "id": "17",
        "name": "The Avengers",
        "genre": "Action, Adventure, Sci-Fi",
        "premiere": "2012-04-11",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_avengers.jpg",
        "projection_type": "3D"
    },
    {
        "id": "18",
        "name": "Jaws",
        "genre": "Adventure, Thriller",
        "premiere": "1975-06-20",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/jaws.jpg",
        "projection_type": "2D"
    },
    {
        "id": "19",
        "name": "The Terminator",
        "genre": "Action, Sci-Fi",
        "premiere": "1984-10-26",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/the_terminator.jpg",
        "projection_type": "2D"
    },
    {
        "id": "20",
        "name": "Back to the Future",
        "genre": "Adventure, Comedy, Sci-Fi",
        "premiere": "1985-07-03",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/back_to_the_future.jpg",
        "projection_type": "2D"
    },
    {
        "id": "21",
        "name": "Raiders of the Lost Ark",
        "genre": "Action, Adventure",
        "premiere": "1981-06-12",
        "duration": "122 min",
        "summary": "Lorem ......",
        "director": "Slavi Vargulev",
        "cast": "Leonardo, Brad, Gosho",
        "image_src": "https://www.example.com/raiders_of_the_lost_ark.jpg",
        "projection_type": "2D"
    }
]

export default MOVIES;